/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: '',
	darkMode: ["class"],
	content: [
		"./src/**/*.{html,js,jsx,ts,tsx}", 
		"components/**/*.{ts,tsx}", 
		"public/index.html",
     	"./@/**/*.{ts,tsx}"
	],
	theme: {
	  extend: {
		colors: {
		  border: "hsl(var(--border))",
		  input: "hsl(var(--input))",
		  ring: "hsl(var(--ring))",
		  background: "hsl(var(--background))",
		  foreground: "hsl(var(--foreground))",
		  primary: {
			DEFAULT: "hsl(var(--primary))",
			foreground: "hsl(var(--primary-foreground))",
		  },
		  secondary: {
			DEFAULT: "hsl(var(--secondary))",
			foreground: "hsl(var(--secondary-foreground))",
		  },
		  destructive: {
			DEFAULT: "hsl(var(--destructive))",
			foreground: "hsl(var(--destructive-foreground))",
		  },
		  muted: {
			DEFAULT: "hsl(var(--muted))",
			foreground: "hsl(var(--muted-foreground))",
		  },
		  accent: {
			DEFAULT: "hsl(var(--accent))",
			foreground: "hsl(var(--accent-foreground))",
		  },
		  popover: {
			DEFAULT: "hsl(var(--popover))",
			foreground: "hsl(var(--popover-foreground))",
		  },
		  card: {
			DEFAULT: "hsl(var(--card))",
			foreground: "hsl(var(--card-foreground))",
		  },
		},
		borderRadius: {
		  lg: `var(--radius)`,
		  md: `calc(var(--radius) - 2px)`,
		  sm: "calc(var(--radius) - 4px)",
		},
	  },
	},
	corePlugins: {
		gridColumn: true,
	},
	plugins: [require("tailwindcss-animate")],
	safelist: [
		// Badge component
		'inline-flex',
		'items-center',
		'rounded-md',
		'border',
		'px-2.5',
		'py-0.5',
		'text-xs',
		'font-semibold',
		'transition-colors',
		'focus:outline-none',
		'focus:ring-2',
		'focus:ring-ring',
		'focus:ring-offset-2',
		'border-transparent',
		'bg-primary',
		'text-primary-foreground',
		'shadow',
		'hover:bg-primary/80',
		'bg-secondary',
		'text-secondary-foreground',
		'hover:bg-secondary/80',
		'bg-destructive',
		'text-destructive-foreground',
		'hover:bg-destructive/80',
		'text-foreground',

		// Command component
		'flex',
		'h-full',
		'w-full',
		'flex-col',
		'overflow-hidden',
		'bg-popover',
		'text-popover-foreground',
		'overflow-hidden',
		'p-0',
		'[&_[cmdk-group-heading]]:px-2',
		'[&_[cmdk-group-heading]]:font-medium',
		'[&_[cmdk-group-heading]]:text-muted-foreground',
		'[&_[cmdk-group]:not([hidden])_~[cmdk-group]]:pt-0',
		'[&_[cmdk-group]]:px-2',
		'[&_[cmdk-input-wrapper]_svg]:h-5',
		'[&_[cmdk-input-wrapper]_svg]:w-5',
		'[&_[cmdk-input]]:h-12',
		'[&_[cmdk-item]]:px-2',
		'[&_[cmdk-item]]:py-3',
		'[&_[cmdk-item]_svg]:h-5',
		'[&_[cmdk-item]_svg]:w-5',
		'border-b',
		'px-3',
		'mr-2',
		'h-4',
		'w-4',
		'shrink-0',
		'opacity-50',
		'h-10',
		'bg-transparent',
		'py-3',
		'text-sm',
		'outline-none',
		'placeholder:text-muted-foreground',
		'disabled:cursor-not-allowed',
		'disabled:opacity-50',
		'max-h-[300px]',
		'overflow-y-auto',
		'overflow-x-hidden',
		'py-6',
		'text-center',
		'p-1',
		'[&_[cmdk-group-heading]]:py-1.5',
		'[&_[cmdk-group-heading]]:text-xs',
		'-mx-1',
		'h-px',
		'bg-border',
		'relative',
		'cursor-default',
		'gap-2',
		'select-none',
		'rounded-sm',
		'px-2',
		'py-1.5',
		'data-[disabled=true]:pointer-events-none',
		'data-[selected=true]:bg-accent',
		'data-[selected=true]:text-accent-foreground',
		'data-[disabled=true]:opacity-50',
		'[&_svg]:pointer-events-none',
		'[&_svg]:size-4',
		'[&_svg]:shrink-0',
		'ml-auto',
		'tracking-widest',

		// Dialog component
		'fixed',
		'inset-0',
		'z-50',
		'bg-black/80',
		'data-[state=open]:animate-in',
		'data-[state=closed]:animate-out',
		'data-[state=closed]:fade-out-0',
		'data-[state=open]:fade-in-0',
		'left-[50%]',
		'top-[50%]',
		'grid',
		'max-w-lg',
		'translate-x-[-50%]',
		'translate-y-[-50%]',
		'gap-4',
		'bg-background',
		'p-6',
		'shadow-lg',
		'duration-200',
		'data-[state=closed]:zoom-out-95',
		'data-[state=open]:zoom-in-95',
		'data-[state=closed]:slide-out-to-left-1/2',
		'data-[state=closed]:slide-out-to-top-[48%]',
		'data-[state=open]:slide-in-from-left-1/2',
		'data-[state=open]:slide-in-from-top-[48%]',
		'sm:rounded-lg',
		'absolute',
		'right-4',
		'top-4',
		'ring-offset-background',
		'transition-opacity',
		'hover:opacity-100',
		'focus:ring-offset-2',
		'data-[state=open]:bg-accent',
		'data-[state=open]:text-muted-foreground',
		'sr-only',
		'space-y-1.5',
		'sm:text-left',
		'flex-col-reverse',
		'sm:flex-row',
		'sm:justify-end',
		'sm:space-x-2',
		'text-lg',
		'leading-none',
		'tracking-tight',
		'text-muted-foreground',

		// Input component
		'border-input',
		'px-3',
		'py-1',
		'text-base',
		'shadow-sm',
		'file:border-0',
		'file:bg-transparent',
		'file:text-sm',
		'file:font-medium',
		'file:text-foreground',
		'focus-visible:outline-none',
		'focus-visible:ring-1',
		'focus-visible:ring-ring',
		'md:text-sm',

		// Select component
		'justify-between',
		'whitespace-nowrap',
		'ring-offset-background',
		'[&>span]:line-clamp-1',
		'justify-center',
		'py-1',
		'max-h-96',
		'min-w-[8rem]',
		'shadow-md',
		'data-[state=closed]:fade-out-0',
		'data-[state=open]:fade-in-0',
		'data-[state=closed]:zoom-out-95',
		'data-[state=open]:zoom-in-95',
		'data-[side=bottom]:slide-in-from-top-2',
		'data-[side=left]:slide-in-from-right-2',
		'data-[side=right]:slide-in-from-left-2',
		'data-[side=top]:slide-in-from-bottom-2',
		'data-[side=bottom]:translate-y-1',
		'data-[side=left]:-translate-x-1',
		'data-[side=right]:translate-x-1',
		'data-[side=top]:-translate-y-1',
		'h-[var(--radix-select-trigger-height)]',
		'min-w-[var(--radix-select-trigger-width)]',
		'pl-2',
		'pr-8',
		'focus:bg-accent',
		'focus:text-accent-foreground',
		'data-[disabled]:pointer-events-none',
		'data-[disabled]:opacity-50',
		'right-2',
		'h-3.5',
		'w-3.5',
		'my-1',
		'bg-muted',

		// Toggle/Toggle Group component
		'gap-1',
		'font-medium',
		'hover:bg-muted',
		'hover:text-muted-foreground',
		'focus-visible:ring-1',
		'data-[state=on]:bg-accent',
		'data-[state=on]:text-accent-foreground',
		'border-input',
		'shadow-sm',
		'hover:bg-accent',
		'hover:text-accent-foreground',
		'px-2',
		'min-w-9',
		'h-8',
		'px-1.5',
		'min-w-8',
		'h-10',
		'px-2.5',
		'min-w-10',

		// Form component
		':grid',
		':gap-2',
		':data-[error=true]:text-destructive',
		':text-muted-foreground',
		':text-destructive',

		// Table component
		'relative',
		'overflow-auto',
		'caption-bottom',
		'[&_tr]:border-b',
		'[&_tr:last-child]:border-0',
		'border-t',
		'bg-muted/50',
		'[&>tr]:last:border-b-0',
		'transition-colors',
		'hover:bg-muted/50',
		'data-[state=selected]:bg-muted',
		'text-left',
		'align-middle',
		'[&:has([role=checkbox])]:pr-0',
		'[&>[role=checkbox]]:translate-y-[2px]',
		'mt-4',
		'flex-row',
		'justify-start',
		'flex-start',
		'ml-2',
		'max-w-sm',

		// Spinner component
		'inline-block',
		'w-8',
		'h-8',
		'w-12',
		'h-12',
		'border-4',
		'border-gray-200',
		'border-t-blue-600',
		'rounded-full',
		'animate-spin',
		'bg-blue-600',
		'animate-pulse',

		// Multiple Selector component
		'cursor-pointer',
		'h-auto',
		'overflow-visible',
		'min-h-10',
		'text-base',
		'focus-within:ring-2',
		'focus-within:ring-ring',
		'focus-within:ring-offset-2',
		'cursor-text',
		'flex-wrap',
		'gap-1',
		'data-[disabled]:bg-muted-foreground',
		'data-[disabled]:text-muted',
		'data-[disabled]:hover:bg-muted-foreground',
		'data-[fixed]:bg-muted-foreground',
		'data-[fixed]:text-muted',
		'data-[fixed]:hover:bg-muted-foreground',
		'ml-1',
		'ring-offset-background',
		'h-3',
		'w-3',
		'text-muted-foreground',
		'hover:text-foreground',
		'flex-1',
		'px-3',
		'py-2',
		'absolute',
		'h-6',
		'w-6',
		'p-0',
		'hidden',
		'top-1',
		'z-10',
		'animate-in',
		'overflow-auto',
		'cursor-default',

		// Modal component
		'items-center',
		'justify-center',
		'p-4',
		'bg-black',
		'bg-opacity-50',
		'bg-white',
		'rounded-lg',
		'shadow-xl',
		'max-w-md',
		'max-w-2xl',
		'max-w-4xl',
		'mx-auto',
		'justify-between',
		'border-gray-200',
		'text-gray-400',
		'hover:text-gray-600',
		'text-2xl',
		'leading-none',
		'text-gray-900',
		'justify-end',
		'gap-3',
		'border-t',

		// List Group component
		'bg-white',
		'divide-y',
		'divide-gray-200',
		'px-4',
		'py-3',
		'text-left',
		'hover:bg-gray-50',
		'bg-blue-50',
		'text-blue-700',
		'border-blue-200',
		'cursor-not-allowed',

		// Label component
		':flex',
		':items-center',
		':gap-2',
		':leading-none',
		':select-none',
		':group-data-[disabled=true]:pointer-events-none',
		':group-data-[disabled=true]:opacity-50',
		':peer-disabled:cursor-not-allowed',
		':peer-disabled:opacity-50',

		// Dropdown component
		'relative',
		'inline-block',
		'bg-blue-600',
		'text-white',
		'hover:bg-blue-700',
		'bg-gray-600',
		'hover:bg-gray-700',
		'bg-green-600',
		'hover:bg-green-700',
		'bg-red-600',
		'hover:bg-red-700',
		'bg-yellow-600',
		'hover:bg-yellow-700',
		'bg-cyan-600',
		'hover:bg-cyan-700',
		'bg-gray-100',
		'text-gray-900',
		'hover:bg-gray-200',
		'bg-gray-800',
		'hover:bg-gray-900',
		'inline-flex',
		'transition-colors',
		'px-3',
		'py-1',
		'px-6',
		'py-3',
		'text-lg',
		'transition-transform',
		'rotate-180',
		'top-full',
		'left-0',
		'mt-1',
		'min-w-48',
		'border-none',

		// Checkbox component
		':peer',
		':border-input',
		':dark:bg-input/30',
		':data-[state=checked]:bg-primary',
		':data-[state=checked]:text-primary-foreground',
		':dark:data-[state=checked]:bg-primary',
		':data-[state=checked]:border-primary',
		':focus-visible:border-ring',
		':focus-visible:ring-ring/50',
		':aria-invalid:ring-destructive/20',
		':dark:aria-invalid:ring-destructive/40',
		':aria-invalid:border-destructive',
		':size-4',
		':rounded-[4px]',
		':shadow-xs',
		':transition-shadow',
		':outline-none',
		':focus-visible:ring-[3px]',
		':disabled:cursor-not-allowed',
		':disabled:opacity-50',
		':justify-center',
		':text-current',
		':transition-none',
		':size-3.5',

		// Card component
		'rounded-lg',
		'border-gray-200',
		'shadow-sm',
		'flex-col',
		'space-y-1.5',
		'text-2xl',
		'text-gray-600',
		'pt-0',

		// Alert component
		'rounded-md',
		'flex',
		'justify-between',
		'bg-blue-50',
		'text-blue-800',
		'border-blue-200',
		'bg-gray-50',
		'text-gray-800',
		'bg-green-50',
		'text-green-800',
		'border-green-200',
		'bg-red-50',
		'text-red-800',
		'border-red-200',
		'bg-yellow-50',
		'text-yellow-800',
		'border-yellow-200',
		'bg-cyan-50',
		'text-cyan-800',
		'border-cyan-200',
		'bg-gray-700',
		'flex-1',
		'ml-4',
		'text-current',
		'hover:opacity-75',

		// Button component (original classes maintained)
		'whitespace-nowrap',
		'font-medium',
		'transition-all',
		'disabled:pointer-events-none',
		'disabled:opacity-50',
		'[&_svg]:pointer-events-none',
		"[&_svg:not([class*='size-'])]:size-4",
		'shrink-0',
		'[&_svg]:shrink-0',
		'outline-none',
		'focus-visible:border-ring',
		'focus-visible:ring-ring/50',
		'focus-visible:ring-[3px]',
		'aria-invalid:ring-destructive/20',
		'dark:aria-invalid:ring-destructive/40',
		'aria-invalid:border-destructive',
		'bg-primary',
		'text-primary-foreground',
		'shadow-xs',
		'hover:bg-primary/90',
		'primary',
		'secondary',
		'success',
		'danger',
		'warning',
		'info',
		'light',
		'dark',
		'outline-primary',
		'outline-secondary',
		'outline-success',
		'outline-danger',
		'outline-warning',
		'outline-info',
		'outline-light',
		'outline-dark',
		'destructive',
		'outline',
		'ghost',
		'link',
		'border-blue-600',
		'text-blue-600',
		'hover:bg-blue-600',
		'hover:text-white',
		'border-gray-600',
		'text-gray-600',
		'hover:bg-gray-600',
		'border-green-600',
		'text-green-600',
		'hover:bg-green-600',
		'border-red-600',
		'text-red-600',
		'hover:bg-red-600',
		'border-yellow-600',
		'text-yellow-600',
		'hover:bg-yellow-600',
		'border-cyan-600',
		'text-cyan-600',
		'hover:bg-cyan-600',
		'border-gray-300',
		'text-gray-700',
		'hover:bg-gray-100',
		'border-gray-800',
		'text-gray-800',
		'hover:bg-gray-800',
		'bg-destructive',
		'hover:bg-destructive/90',
		'focus-visible:ring-destructive/20',
		'dark:focus-visible:ring-destructive/40',
		'dark:bg-destructive/60',
		'bg-background',
		'hover:bg-accent',
		'hover:text-accent-foreground',
		'dark:bg-input/30',
		'dark:border-input',
		'dark:hover:bg-input/50',
		'dark:hover:bg-accent/50',
		'dark:hover:bg-accent/70',
		'text-primary',
		'underline-offset-4',
		'hover:underline',
		'h-9',
		'px-4',
		'py-2',
		'has-[>svg]:px-3',
		'h-8',
		'rounded-md',
		'gap-1.5',
		'px-3',
		'has-[>svg]:px-2.5',
		'h-10',
		'px-6',
		'has-[>svg]:px-4',
		'size-9',
	]
  }
  