// <auto-generated />
using GrantTracker.Dal.EmployeeDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrantTracker.Migrations.InterfaceDb
{
    [DbContext(typeof(InterfaceDbContext))]
    [Migration("20220619160806_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GrantTracker.Dal.EmployeeDb.Employee", b =>
                {
                    b.Property<string>("Department")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("char(60)")
                        .HasColumnName("department")
                        .IsFixedLength();

                    b.Property<string>("Domain")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("domain")
                        .IsFixedLength();

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("emailAddress")
                        .IsFixedLength();

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("employeeID")
                        .IsFixedLength();

                    b.Property<string>("GivenName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("givenName")
                        .IsFixedLength();

                    b.Property<string>("LocationCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("locationCode")
                        .IsFixedLength();

                    b.Property<string>("MiddleName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("middleName")
                        .IsFixedLength();

                    b.Property<string>("SamAccountName")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("samAccountName")
                        .IsFixedLength();

                    b.Property<string>("Sn")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("sn")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("char(40)")
                        .HasColumnName("title")
                        .IsFixedLength();

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
