using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GrantTracker.Migrations.SynergyEOD
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "rev");

            migrationBuilder.CreateTable(
                name: "REV_ORGANIZATION",
                schema: "rev",
                columns: table => new
                {
                    ORGANIZATION_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    PARENT_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    IS_LEAF = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    TYPE = table.Column<string>(type: "nvarchar(2)", maxLength: 2, nullable: true),
                    ORGANIZATION_NAME = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    ADDRESS_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    PHONE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    PHONE2 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    CHANGE_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CHANGE_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    ORGANIZATION_ABBR_NAME = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true, comment: "Abbreviated Organization Name"),
                    ALLOW_AS_VIRTUAL_ROOT_NODE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Used to determine which Organization nodes appear in the drop-down list of Virtual Root Nodes"),
                    WEBSITE_URL = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true, comment: "an Organization's website"),
                    HIDE_ORGANIZATION = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    CENTRAL_PRINT_ID = table.Column<string>(type: "nvarchar(55)", maxLength: 55, nullable: true),
                    DEFAULT_EMAIL = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    EDFI_KEY_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    EDFI_DISTRICT_ID = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    ADD_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    INCLUDE_ONEROSTER_API = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    EDFI_ALT_KEY_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("REV_ORGANIZATION_P", x => x.ORGANIZATION_GU);
                });

            migrationBuilder.CreateTable(
                name: "REV_PERSON",
                schema: "rev",
                columns: table => new
                {
                    PERSON_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    LAST_NAME = table.Column<string>(type: "nvarchar(60)", maxLength: 60, nullable: false, comment: "LN"),
                    FIRST_NAME = table.Column<string>(type: "nvarchar(60)", maxLength: 60, nullable: false, comment: "FN"),
                    MIDDLE_NAME = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true, comment: "MN"),
                    TITLE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    SUFFIX = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "Append to LN"),
                    GENDER = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "SX"),
                    SOCIAL_SECURITY_NUMBER = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    EMAIL = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    BIRTH_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "BD"),
                    BIRTH_PLACE = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: true, comment: "BP"),
                    ETHNIC_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "EC"),
                    PRIMARY_LANGUAGE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    US_CITIZEN = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    COUNTRY_OF_CITIZENSHIP = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "BC"),
                    NON_CITIZEN_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    JOB_TITLE = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    HOME_ADDRESS_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    MAIL_ADDRESS_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    WORK_ADDRESS_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    PRIMARY_PHONE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "Read only BO Property - updated from rev person phone - redundant data to provide quick access to the persons main phone number info used in most reports"),
                    PRIMARY_PHONE_EXTN = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true, comment: "Read only BO Property - updated from rev person phone - redundant data to provide quick access to the persons main phone number info used in most reports"),
                    PRIMARY_PHONE_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Read only BO Property - updated from rev person phone - redundant data to provide quick access to the persons main phone number info used in most reports"),
                    PRIMARY_PHONE_LISTED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Read only BO Property - updated from rev person phone - redundant data to provide quick access to the persons main phone number info used in most reports"),
                    PRIMARY_PHONE_CONTACT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Read only BO Property - updated from rev person phone - redundant data to provide quick access to the persons main phone number info used in most reports"),
                    DECEASED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Indicates if a person is living or dead"),
                    SCROLL_COMPOSITE_KEY = table.Column<string>(type: "nvarchar(160)", maxLength: 160, nullable: true),
                    SCROLL_COMPOSITE_KEY_UPDATE = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    SCROLL_SOUNDEX = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    AKA_LAST_NAME = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true, comment: "LN"),
                    AKA_FIRST_NAME = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true, comment: "FN"),
                    AKA_MIDDLE_NAME = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true, comment: "MN"),
                    AKA_SUFFIX = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "Append to LN"),
                    PRIMARY_LANGUAGE_OTHER = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    CHANGE_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CHANGE_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    HISPANIC_INDICATOR = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    RESOLVED_ETHNICITY_RACE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "The person's federal ethnic code"),
                    STATE_ETHNICITY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    NICK_NAME = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    LAST_NAME_GOES_BY = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true),
                    PREVIOUS_SOCIAL_SECURITY_NUM = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    PRIMARY_RACE_INDICATOR = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    EDFI_ID = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    PRIMARY_PHONE_ACCEPT_TEXT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    DECEASED_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SUFFIX_DD = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    LEGAL_FN = table.Column<string>(type: "nvarchar(60)", maxLength: 60, nullable: true),
                    LEGAL_MN = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true),
                    LEGAL_LN = table.Column<string>(type: "nvarchar(60)", maxLength: 60, nullable: true),
                    LEGAL_SX = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    GENDER_NON_BINARY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PRIMARY_PHONE_COMM_LEVEL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PRIMARY_TEXT_COMM_LEVEL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    EMAIL_REQ_VALID_DATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    EMAIL_VALID_DATE = table.Column<DateTime>(type: "datetime", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("REV_PERSON_P", x => x.PERSON_GU);
                });

            migrationBuilder.CreateTable(
                name: "REV_YEAR",
                schema: "rev",
                columns: table => new
                {
                    YEAR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SCHOOL_YEAR = table.Column<decimal>(type: "numeric(4,0)", nullable: false),
                    EXTENSION = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    CHANGE_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    CHANGE_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ADD_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    ADD_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("REV_YEAR_P", x => x.YEAR_GU);
                });

            migrationBuilder.CreateTable(
                name: "REV_ORGANIZATION_YEAR",
                schema: "rev",
                columns: table => new
                {
                    ORGANIZATION_YEAR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ORGANIZATION_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    YEAR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    CHANGE_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    CHANGE_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ADD_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    ADD_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("REV_ORGANIZATION_YEAR_P", x => x.ORGANIZATION_YEAR_GU);
                    table.ForeignKey(
                        name: "REV_ORGANIZATION_YEAR_F1",
                        column: x => x.ORGANIZATION_GU,
                        principalSchema: "rev",
                        principalTable: "REV_ORGANIZATION",
                        principalColumn: "ORGANIZATION_GU");
                    table.ForeignKey(
                        name: "REV_ORGANIZATION_YEAR_F2",
                        column: x => x.YEAR_GU,
                        principalSchema: "rev",
                        principalTable: "REV_YEAR",
                        principalColumn: "YEAR_GU");
                });

            migrationBuilder.CreateTable(
                name: "EPC_STU",
                schema: "rev",
                columns: table => new
                {
                    STUDENT_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    SIS_NUMBER = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false, comment: "ID"),
                    STATE_STUDENT_NUMBER = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true, comment: "SI: SAIS"),
                    HOME_LANGUAGE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "HL"),
                    MIGRANT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "MG"),
                    IMMIGRATION_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    ORIGINAL_ENTER_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    FINAL_WITHDRAWAL_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "Date left disctict; upon reactivation clear this date; The leave date or summer withdrawl date"),
                    GRID_CODE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "Used during address validation - GC"),
                    CUSTODY_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "CD"),
                    SPECIAL_ED_SCREENING_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "SG"),
                    BIRTH_STATE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "BS"),
                    BIRTH_COUNTRY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "BC"),
                    BIRTH_VERIFICATION = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "BV"),
                    BIRTH_CERTIFICATE_NUM = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    INTERNET_AUTHORIZATION = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "IN"),
                    EXCESSIVE_DEBT_INDICATOR = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Yes - prevents mailing of grade/progress reports: DB"),
                    DIRECTORY_LIST_EXCLUDE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Exclude student info for outside directory list (such as military): DT"),
                    FAMILY_CODE = table.Column<string>(type: "nvarchar(7)", maxLength: 7, nullable: true, comment: "Type of family (one parent, two parent, etc.): EM"),
                    CRITICAL_ILLNESS = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "CI"),
                    BILINGUAL_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "temp code - BL"),
                    BILINGUAL_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "temp date - BL"),
                    GENERAL_EQUIVALENCY_DIPLOMA = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "GE"),
                    EXPECTED_GRADUATION_YEAR = table.Column<decimal>(type: "numeric(4,0)", nullable: true, comment: "GY - 5 years + 9th grade; calendar year in which you graduate"),
                    EXPECTED_GRADUATION_MONTH = table.Column<decimal>(type: "numeric(2,0)", nullable: true),
                    GRAD_REQ_DEF_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ENROLLMENT_RESTRICTION_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "XT: Expelled students trying to re-enroll at another school; SASI3 blinks the name"),
                    ENROLLMENT_RESTRICTION_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "XD: The date teh restriction code was implemented"),
                    ENR_RESTRICT_ORGANIZATION_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    NOTES = table.Column<string>(type: "ntext", nullable: true),
                    PSYCHOLOGICAL_SCREENING = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DWELLING_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CLASS_OF = table.Column<decimal>(type: "numeric(4,0)", nullable: true),
                    OWNED_BY_GENESIS = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Used by New Year Rollover from other SIS, does Synergy own this student"),
                    HOME_LESS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Renamed from ASTU.FAMILY_LINK"),
                    GRADUATION_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "ASTU.GRAD_DT is not used in Elementary"),
                    MEDICAID = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "ASTU.GETS_AID - Called Medical in California"),
                    ORIGINAL_ENTER_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "ASTU.ORIG_ENTER_DT, Lookup ENTER_CODE"),
                    ORIGINAL_STATE_ENTER_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    ORIGINAL_ENTER_GRADE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    US_ENTRY_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "First date student entered the US"),
                    US_ENTRY_DATE_SCHOOL = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "First date student entered a school in the US"),
                    US_ENTRY_FROM_COUNTRY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Country student came from when entering the US for the first time"),
                    ADDRESS_CHG_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    MAIL_SAME_AS_HOME_ADDRESS = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Mail address is same as home address"),
                    NO_PHONE_NEEDED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Mandatory to add telephone with option for no phone"),
                    HOME_LANGUAGE_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    PRIMARY_LANGUAGE_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    PREV_SCHOOL_ID = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "Previous School Entity ID"),
                    PREV_STATE_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Previous State Code"),
                    PREV_SCHOOL_STATE_ID = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true, comment: "Previous school State ID"),
                    TRANSCRIPT_COMMENT = table.Column<string>(type: "ntext", nullable: true),
                    SIG_STU_DATA_CHANGE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    STATE_STU_NUM_SUBMITTED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Flag indicating if a request was sent to the state requesting the state number"),
                    USER_CODE_1 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "User-defined code value"),
                    USER_CODE_2 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "User-defined code value"),
                    USER_CODE_3 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "User-defined code value"),
                    USER_CODE_4 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "User-defined code value"),
                    USER_CODE_5 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "User-defined code value"),
                    USER_CODE_6 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "User-defined code value"),
                    USER_CODE_7 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "User-defined code value"),
                    USER_CODE_8 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "User-defined code value"),
                    SCHOOLING_IN_US = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Foreign born schooling in the United States less than or equal to 3 academic years"),
                    BIRTH_SPECIAL_CIRCUMSTANCES = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "If the child was born in a foreign country and granted U.S. citizenship"),
                    GRADUATION_STATUS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "K12."),
                    POST_SECONDARY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ALT_ID_1 = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    ALT_ID_2 = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    REFUGEE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    FOSTER_HOME = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    MIGRANT_STUDENT_ID = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    BIRTH_VERIFICATION_OTHER = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    DWELLING_TYPE_OTHER = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    CHANGE_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CHANGE_DATE_TIME_STAMP = table.Column<DateTime>(type: "datetime", nullable: true),
                    ADD_DATE_TIME_STAMP = table.Column<DateTime>(type: "datetime", nullable: true),
                    ADD_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    PROF_ATHLETE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    PARTNERSHIP_ACADEMY_ID = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CTE_PATHWAY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CTE_PATHWAY_COMPLETER = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    TEEN_PARENT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    DISPLACED_HOMEMAKER = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    INDICATOR_ELL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    INDICATOR_SPECED = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    INDICATOR_1 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    INDICATOR_2 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    INDICATOR_3 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    INDICATOR_4 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    INDICATOR_5 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    INDICATOR_6 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    INDICATOR_7 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    INDICATOR_8 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    OPT_OUT_MILITARY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "A customized drop down list of opt out reasons"),
                    OPT_OUT_FAMILY_LIFE_ED = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "A customized drop down list of opt out reasons"),
                    OPT_OUT_GUIDANCE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "A customized drop down list of opt out reasons"),
                    OPT_OUT_PHOTO_RELEASE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "A customized drop down list of opt out reasons"),
                    OPT_OUT_MEDICAL_STATE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    OPT_OUT_MEDICAL_FED = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    OPT_OUT_DIRECTORY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "A customized drop down list of opt out reasons"),
                    ENR_RESTR_INCL_EXCL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "If school types are included/excluded in the enrollment restrictions."),
                    ANONYMOUS_STU_ID = table.Column<decimal>(type: "numeric(18,0)", nullable: true),
                    INIT_NINTH_GRADE_YEAR = table.Column<decimal>(type: "numeric(4,0)", nullable: true),
                    PRIMARY_COMM_FAMILY_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ENROLL_RESIDENT_FAMILY_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ENROLL_LESS_THREE_OVR = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    VC_REQ = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DISADVANTAGED = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    EARLY_COLLEGE_SCHOLAR = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIPLOMA_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    GRADUATION_PLAN = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    EXCLUDE_FROM_AUTO_FTE_CALC = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SPED_WEEKLY_TIME_PERCT = table.Column<decimal>(type: "numeric(3,0)", nullable: true),
                    WHEELCHAIR = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    UC_GRAD_REQ = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PUBLIC_SCH_ST_YR = table.Column<decimal>(type: "numeric(4,0)", nullable: true),
                    CHILD_HOLD_ENROLLMENT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    CHILD_INITIAL_SCHOOL = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CHILD_INITAL_GRADE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIPLOMA_SEAL = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    OLD_STATE_STUDENT_NUMBER = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    GP_ELIG_WAIV_DT_HS = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    GP_ELIG_WAIV_DT_MS = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    INIT_NINTH_GRADE_YEAR_DT = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    PERSPECTIVE_COLLEGE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    HAS_INTERNET_AT_HOME = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIPLOMA_ATTEMPT_TYPE_1 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIPLOMA_ATTEMPT_TYPE_2 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIPLOMA_ATTEMPT_TYPE_3 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DISTRICT_OF_RESIDENCE_ADDR = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    HOME_COUNTY = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    CALL_ORDER = table.Column<decimal>(type: "numeric(2,0)", nullable: true),
                    GRADUATION_SEMESTER = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CREDENTIAL_TYPE_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    MONTHS_US_ATTENDANCE = table.Column<int>(type: "int", nullable: true),
                    MONTHS_NON_US_ATTENDANCE = table.Column<int>(type: "int", nullable: true),
                    RELATION_SELECT_RACE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    RACE_SELECTION_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    CSAP_ALTERNATE_ASSESS = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    VAL_DEL_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    VAL_DEL_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CERT_GEN_STUDIES = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    CREDIT_ACCOMMODATION = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SUMMER_GRAD = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    FOSTER_ID = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    BIRTH_COUNTY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_TEXT_1 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ALLOW_MEDICAL_TREATMENT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    REQ_STATE_STUDENT_NUMBER = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    REQ_STATE_STU_NUM = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    MILITARY_FAMILY_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CDW_PRESCRIBED_LOAD_OFFSET = table.Column<decimal>(type: "numeric(7,4)", nullable: true),
                    MSIX_NUMBER = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    TECH_PREP_STATUS = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    INTERPRETER_NEEDED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    OVERRIDE_CONT_AND_FUNDING = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    PARENTAL_STATUS_CODE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    TITLE_3_ENTRY_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    PUSH_NOTE_ATT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    PUSH_NOTE_ASSIGN = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    PUSH_NOTE_GRADE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    PUSH_NOTE_HEALTH = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    PUSH_NOTE_DISCP = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    PUSH_ASSIGN_CUTOFF = table.Column<decimal>(type: "numeric(3,0)", nullable: true),
                    PUSH_GRADE_CUTOFF = table.Column<decimal>(type: "numeric(3,0)", nullable: true),
                    IMMIGRANT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    MIDDLE_NAME_VERIFICATION = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_DATETIMEVAL_01 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    LOC_AWARD_CRD = table.Column<decimal>(type: "numeric(2,0)", nullable: true),
                    SPEC_PERM_LOC_AWARD_CRD = table.Column<decimal>(type: "numeric(2,0)", nullable: true),
                    CRD_ACCOMMODATION_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_NUM_01 = table.Column<decimal>(type: "numeric(12,3)", nullable: true),
                    POST_SEC_SURVEY = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    CERTIFICATION_OF_COMPLETION = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIPLOMA_DESIGNATION = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ONLINE_CRS_EXEMPT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    MILITARY_ENLISTED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    DEVICE_ACCESS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    INT_ACC_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    INT_PERF = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIGITAL_DEVICE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIG_DEVICE_ACC = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    YEARS_IN_US_SCH = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIG_DEVICE_PROV = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    RETIRED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    INDICATOR_504 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DIPLOMA_OPTION = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    INT_ACC_BARRIER = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_DD_01 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    IB_DIPLOMA = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    AICE_DIPLOMA = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    EARLY_GRAD = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ASSOCIATE_DEGREE = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    AP_CAPSTONE_DIPLOMA = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    EARNED_BILITERACY_SEAL = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_USER_CHECK_01 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SURVEY_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    GRAD_REQ_BASIS = table.Column<string>(type: "varchar(2)", unicode: false, maxLength: 2, nullable: true),
                    COMM_DATE_PASSED_FOR_GRAD = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    MATH_DATE_PASSED_FOR_GRAD = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    CERT_OF_CMPLT_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    COLLEGE_READY_DIPLOMA = table.Column<string>(type: "varchar(1)", unicode: false, maxLength: 1, nullable: true),
                    ADV_INTL_CERT_PRGM = table.Column<string>(type: "varchar(1)", unicode: false, maxLength: 1, nullable: true),
                    NATL_MERIT_SCHOLAR = table.Column<string>(type: "varchar(1)", unicode: false, maxLength: 1, nullable: true),
                    NATL_ACHIEVE_SCHOLAR = table.Column<string>(type: "varchar(1)", unicode: false, maxLength: 1, nullable: true),
                    NATL_HISP_SCHOLAR = table.Column<string>(type: "varchar(1)", unicode: false, maxLength: 1, nullable: true),
                    ADULT_ED_DIPLOMA_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ADULT_ED_DIPLOMA_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    ADULT_ED_CERT_OF_COMP = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("EPC_STU_P", x => x.STUDENT_GU);
                    table.ForeignKey(
                        name: "EPC_STU_F1",
                        column: x => x.STUDENT_GU,
                        principalSchema: "rev",
                        principalTable: "REV_PERSON",
                        principalColumn: "PERSON_GU");
                    table.ForeignKey(
                        name: "EPC_STU_F2",
                        column: x => x.ENR_RESTRICT_ORGANIZATION_GU,
                        principalSchema: "rev",
                        principalTable: "REV_ORGANIZATION",
                        principalColumn: "ORGANIZATION_GU");
                    table.ForeignKey(
                        name: "EPC_STU_F6",
                        column: x => x.CHILD_INITIAL_SCHOOL,
                        principalSchema: "rev",
                        principalTable: "REV_ORGANIZATION_YEAR",
                        principalColumn: "ORGANIZATION_YEAR_GU");
                });

            migrationBuilder.CreateTable(
                name: "EPC_STU_SCH_YR",
                schema: "rev",
                columns: table => new
                {
                    STUDENT_SCHOOL_YEAR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    STUDENT_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ORGANIZATION_YEAR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    YEAR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: false, comment: "Need to be able to read all stu school year rows for a given student by year - to do validation"),
                    REPORTED_TO_STATE_NOSHOW = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    REPORTED_TO_STATE_LEAVE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    OLD_SIS_STUDENT_NUM = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "SN"),
                    GRADE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Uses bubble up theory"),
                    GRADE_EXIT_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    USER_CODE1 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    USER_CODE2 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    USER_CODE3 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    USER_CODE4 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    USER_CODE5 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    USER_CODE6 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    USER_CODE7 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    USER_CODE8 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    USER_CODE9 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    ENTER_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "Uses bubble up theory"),
                    ENTER_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Uses bubble up theory"),
                    LEAVE_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "Last day of enrollment - Uses bubble up theory"),
                    LEAVE_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Uses bubble up theory"),
                    HOMEROOM_SECTION_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    LAST_HOMEROOM_SECTION_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    INSTRUCTIONAL_SETTING = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Uses bubble up theory"),
                    COUNSELOR_SCHOOL_YEAR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true, comment: "CU"),
                    LOCKER_NUMBER = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "LK"),
                    TRACK_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true, comment: "bubble up theory"),
                    PROGRAM_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "bubble up theory"),
                    EXTEND_LEARNING_PROGRAM = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Will eventually reside in Needs - for now here so we can populate back to SASI3: EL"),
                    SPECIAL_ENROLLMENT_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "bubble up theory"),
                    ACCESS_504 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "bubble up theory"),
                    SPECIAL_PROGRAM_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "bubble up theory"),
                    VOCATIONAL = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "VO - go away when CTE module implemented"),
                    IVEP = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "IV: go away when CTE module implemented"),
                    TECH_PREP = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "TE: go away when CTE module implemented"),
                    YEAR_END_STATUS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "YE - SAIS"),
                    BUS_ROUTE_TO_SCHOOL = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true, comment: "AB"),
                    BUS_ROUTE_FROM_SCHOOL = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true, comment: "PB"),
                    TUTION_PAYER_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "bubble up theory"),
                    NEXT_SCHOOL_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true, comment: "NS"),
                    NEXT_GRADE_LEVEL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "NG"),
                    HAS_CHANGED_FLAG = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "This is set to Y when something relevant has changed that will cause a form print (whatever we determine \"form\" means)"),
                    STATUS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "TG - SASI3 status flag"),
                    HOMEBOUND = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "bubble up theory"),
                    DISTRICT_OF_RESIDENCE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "bubble up theory"),
                    FTE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "bubble up theory"),
                    SUMMER_WITHDRAWL_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "ATS.LC; ATS.EC make \"E3\""),
                    SUMMER_WITHDRAWL_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "ATS.LD as first day of the calendar; ATS.ED also first day of calendar"),
                    TITLE_1_PROGRAM = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "C1 - will eventually be moved to needs to be time tracked"),
                    TITLE_1_SERVICE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "C2 byte 1 - will eventually be moved to needs to be time tracked"),
                    TITLE_1_EXIT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "C2 byte 2 - will eventually be moved to needs to be time tracked"),
                    LAST_ACTIVITY_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "Uses bubble up theory, is the last activity date.  Any new activity must be greater than or equal to this date."),
                    LAST_SCHOOL_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    EXCLUDE_ADA_ADM = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ALLOW_TYLENOL = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    ALLOW_MEDICATION = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ATTEND_PERMIT_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "SASIxp Reason for Attendance code, Lookup ATP"),
                    ATTEND_PERMIT_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "SASIxp Reason for Attendance date"),
                    SCHOOL_RESIDENCE_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true, comment: "ASTU.SCHL_RESIDENCE"),
                    NEXT_TRACK_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true, comment: "ASTU.NEXT_TRK Only visible for schools with more than 1 track."),
                    FORBID_AUTO_DIAL = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "ASTU.AUTO_DIAL"),
                    NO_SHOW_STUDENT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SCHED_HOUSE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "Scheduling house K12.MassScheduling.HOUSE"),
                    SCHED_TEAM = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "Scheduling Team K12.MassScheduling.TEAM"),
                    SCHED_EXEMPT_HOUSE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Do not require student to have the same house for all house marked sections"),
                    SCHED_EXEMPT_TEAM = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Do not require student to have the same team for all team marked sections"),
                    SCHED_LOW_PERIOD = table.Column<decimal>(type: "numeric(3,0)", nullable: true, comment: "scheduling low period limit for this student (no classes to be scheduled below this period number)"),
                    SCHED_HIGH_PERIOD = table.Column<decimal>(type: "numeric(3,0)", nullable: true, comment: "scheduling high period limit for this student (no classes to be scheduled above this period number)"),
                    SCHED_BALANCE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "Value to influence the balancing of scheduling classes"),
                    SCHED_STAMP = table.Column<DateTime>(type: "datetime", nullable: true, comment: "Last date/time the student course request(s) was changed  upon updating this stamp, also update stamp in school year opt"),
                    WITHDRAWAL_REASON_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Withdrawal Reason Code"),
                    DENY_PHOTO_INTERVIEW = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ABS_REPORT_POLICY = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    STATEMENT_OF_AWARENESS = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    REGISTRATION_RECEIVED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    REGISTRATION_UPDATED = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    CAME_FROM = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    MOVED_TO = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    ENR_USER_1 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ENR_USER_2 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ENR_USER_3 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ENR_USER_DD_4 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ENR_USER_DD_5 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ENR_USER_DD_6 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ENR_USER_NUM_1 = table.Column<decimal>(type: "numeric(8,3)", nullable: true, comment: "Added for state specific uses.  Must bubble-up."),
                    ENR_USER_NUM_2 = table.Column<decimal>(type: "numeric(8,3)", nullable: true, comment: "Added for state specific uses.  Must bubble-up."),
                    ENR_USER_NUM_3 = table.Column<decimal>(type: "numeric(8,3)", nullable: true, comment: "Added for state specific uses.  Must bubble-up."),
                    ENR_USER_NUM_4 = table.Column<decimal>(type: "numeric(8,3)", nullable: true, comment: "Added for state specific uses.  Must bubble-up."),
                    ENR_USER_NUM_5 = table.Column<decimal>(type: "numeric(8,3)", nullable: true, comment: "Added for state specific uses.  Must bubble-up."),
                    ENR_USER_CHECK_1 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Added for state specific uses.  Must bubble-up."),
                    ENR_USER_CHECK_2 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Added for state specific uses.  Must bubble-up."),
                    ENR_USER_CHECK_3 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false, comment: "Added for state specific uses.  Must bubble-up."),
                    USER_NUM1 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    USER_NUM2 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    USER_NUM3 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    USER_NUM4 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    USER_NUM5 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    USER_NUM6 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    USER_NUM7 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    USER_NUM8 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    USER_DATE1 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    USER_DATE2 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    USER_DATE3 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    USER_DATE4 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    USER_CHECK1 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    USER_CHECK2 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    USER_CHECK3 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    USER_CHECK4 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    USER_CHECK5 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    USER_CHECK6 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    USER_CHECK7 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    USER_CHECK8 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    TRANSPORTATING_DISTRICT = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true, comment: "Transporting district number.  Used in MN MARSS.  Uses the same lookup as MARSS district of residence."),
                    PXP_OCR_LOCKED_IN = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    PXP_OCR_LOCKED_IN_DT = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    PXP_OCR_VALIDATED = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: false),
                    PXP_OCR_VALIDATED_DT = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    RECEIVER_SCHOOL = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    SPEC_ED_SCH_OF_ATT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    OVERRIDE_FORCE_STS = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    CAHSEE_ELA_RETAKE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    CAHSEE_MATH_RETAKE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SUMMER_SCHOOL_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true, comment: "NS"),
                    SUMMER_GRADE_LEVEL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "NG"),
                    DISTRICT_SPED_ACCOUNT = table.Column<string>(type: "nvarchar(7)", maxLength: 7, nullable: true),
                    ENR_USER_DD_1 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    ENR_USER_DD_2 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    ENR_USER_DD_3 = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    PICK_UP_TRANSPORT_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Type of transport used for pickup from school"),
                    PICK_UP_BUS_STOP = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true, comment: "Bus stop to be picked up at"),
                    PICK_UP_TRANSPORT_TIME = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "Time of pickup"),
                    PICK_UP_COMMENT = table.Column<string>(type: "text", nullable: true, comment: "Notes about the pickup from school"),
                    PICK_UP_LOCATION_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Type of location of the pickup"),
                    PICK_UP_ADDRESS_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true, comment: "GUID for the pickup address"),
                    DROP_OFF_TRANSPORT_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Type of transport used for drop off to school"),
                    DROP_OFF_BUS_STOP = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true, comment: "Bus stop to be dropped off up at"),
                    DROP_OFF_TRANSPORT_TIME = table.Column<DateTime>(type: "smalldatetime", nullable: true, comment: "Time of drop off"),
                    DROP_OFF_COMMENT = table.Column<string>(type: "text", nullable: true, comment: "Notes about the drop off to school"),
                    DROP_OFF_LOCATION_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Type of location of the drop off"),
                    DROP_OFF_ADDRESS_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true, comment: "GUID for the drop off address"),
                    SPEC_TRANS_REQ_COMMENT = table.Column<string>(type: "text", nullable: true, comment: "Description of the reasons for special transportation"),
                    TRANSPORT_ELIGIBLE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true, comment: "Code that indicates student's eligiblity for transportation"),
                    PICK_UP_SCHOOL_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DROP_OFF_SCHOOL_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    COMPLETION_STATUS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PICK_UP_TRANS_REAS_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PICK_UP_TRANS_REAS_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    DROP_OFF_TRANS_REAS_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DROP_OFF_TRANS_REAS_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    CHANGE_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    CHANGE_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ADD_DATE_TIME_STAMP = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    ADD_ID_STAMP = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    EXP_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    EXP_TIME_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CB_LAST_REQUEST_UPDATE = table.Column<DateTime>(type: "datetime", nullable: true),
                    RESPON_DISTRICT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    RESPON_SCHOOL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SERV_DISTRICT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SERV_SCHOOL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SCHOOL_CHOICE_STATUS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    FULL_TIME_VIRTUAL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    LEAVE_UNATTENDED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SCH_START_TIME = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SCH_DISMISS_TIME = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    PICK_UP_RESP_PERSON = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    PICK_UP_RESP_PHONE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    DROP_OFF_RESP_PERSON = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    DROP_OFF_RESP_PHONE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    SPCL_PRGM_TCH_SCH_YR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    TRANSPORT_REQUEST_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    TRANSPORT_START_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    ENTERED_BY_USER = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    NEXT_SCH_ATTEND = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SPED_1ST_SEM_REIMBRSMNT = table.Column<decimal>(type: "numeric(9,2)", nullable: true),
                    SPED_2ND_SEM_REIMBRSMNT = table.Column<decimal>(type: "numeric(9,2)", nullable: true),
                    TRUANCY_CONFERENCE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_USER_CODE_DD_01 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_02 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_03 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_04 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_05 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_06 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_07 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_08 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_09 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_10 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_11 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_12 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_13 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_14 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_15 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_16 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_17 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_18 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_19 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_20 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CHECK_01 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_USER_CHECK_02 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_USER_CHECK_03 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_USER_CHECK_04 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_USER_CHECK_05 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_NUM_01 = table.Column<decimal>(type: "numeric(8,3)", nullable: true),
                    SR_ENR_USER_NUM_02 = table.Column<decimal>(type: "numeric(8,3)", nullable: true),
                    SR_ENR_USER_NUM_03 = table.Column<decimal>(type: "numeric(8,3)", nullable: true),
                    SR_ENR_USER_NUM_04 = table.Column<decimal>(type: "numeric(8,3)", nullable: true),
                    SR_ENR_USER_NUM_05 = table.Column<decimal>(type: "numeric(8,3)", nullable: true),
                    SR_ENR_USER_DD_01 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_02 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_03 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_04 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_05 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_06 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_07 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_08 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_09 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_10 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_11 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_12 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_13 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_14 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_15 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_16 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_17 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_18 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_19 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_20 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_CHECK_01 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_02 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_03 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_04 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_05 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_06 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_07 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_08 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_09 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_10 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    OPT_OUT_MEDICAL_STATE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    OPT_OUT_MEDICAL_FED = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SCH_COMPL_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SPED_REIMBRSMNT_DSBLT_CD = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SPED_SUM_SEM_REIMBRSMNT = table.Column<decimal>(type: "numeric(9,2)", nullable: true),
                    SR_ENR_TEXT_1 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_ENR_TEXT_2 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_ENR_TEXT_3 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_ENR_TEXT_4 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_ENR_TEXT_5 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_ENR_TEXT_6 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_ENR_TEXT_7 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_ENR_TEXT_8 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_ENR_TEXT_9 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_ENR_TEXT_10 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_DATE_1 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SR_USER_DATE_2 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SR_USER_DATE_3 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SR_USER_DATE_4 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SR_USER_DATE_5 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SR_USER_NUM_1 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    SR_USER_NUM_2 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    SR_USER_NUM_3 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    SR_USER_NUM_4 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    SR_USER_NUM_5 = table.Column<decimal>(type: "numeric(10,2)", nullable: true),
                    SR_USER_TEXT_1 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_TEXT_2 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_TEXT_3 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_TEXT_4 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_TEXT_5 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_TEXT_6 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_TEXT_7 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_TEXT_8 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_TEXT_9 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SR_USER_TEXT_10 = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    MILITARY_COMPACT_STATUTE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SUB_SCHOOL = table.Column<decimal>(type: "numeric(10,0)", nullable: true),
                    COLLEGE_ENROLLED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    PREVIOUS_LOCATION_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PREVIOUS_YEAR_END_STATUS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    STU_CTDS_NUMBER = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    REPORTING_SCHOOL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    COUNTY_RESIDENT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    PREV_IN_GRADE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    COUNTY_RESIDENT_NEW = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    NON_RESIDENT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    CONTINUOUS_STATE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CONTINUOUS_SCHOOL = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CONTINUOUS_DISTRICT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    STATE_FUNDING_STATUS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    STU_INSTRUCTIONAL_HOURS = table.Column<decimal>(type: "numeric(6,2)", nullable: true),
                    SR_ENR_USER_DATE_01 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SR_ENR_USER_DATE_02 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SR_ENR_USER_DATE_03 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SR_ENR_USER_DATE_04 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SR_ENR_USER_DATE_05 = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    PUPIL_ATT_INFO = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ALLOW_IBUPROFEN = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    INIT_NINTH_GRADE_YEAR = table.Column<decimal>(type: "numeric(4,0)", nullable: true),
                    ENR_PATHWAY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    NEXT_ENR_PATHWAY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    NYR_EXCLUDE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    BUS_ESTIMATED_MILEAGE = table.Column<decimal>(type: "numeric(6,2)", nullable: true),
                    COURSE_OF_STUDY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DROP_OFF_BUS_NUMBER = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    PICK_UP_BUS_NUMBER = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    STANDARD_DAY_MINUTES = table.Column<int>(type: "int", nullable: true),
                    EMPLOYED_WHILE_ENROLLED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    HOME_SCHOOLED = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    MILITARY_CONNECTION = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PK_FUNDING_SOURCE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    MANUAL_FTE_OVERRIDE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    OVERRIDE_CONT_AND_FUNDING = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SMR_WITHDRAWAL_REASON_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_21 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_22 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    EXC_FRM_AUTO_CALC_FTE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    DRP_PARTICIPANT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    ADMINISTRATOR_SCH_YR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ALT_EDU_STU = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    FOSTER_HOME = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    IMMIGRANT = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    NIGHTTIME_RESIDENCE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    REFUGEE = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    RESIDENT_DISTRICT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    RESIDENT_TOWN = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    UNACCOMPANIED_YOUTH = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    STATE_GRADE_LVL_OVERRIDE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ATT_PLAN_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    ATT_CONF_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    COURT_REFERRAL_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    STATE_ENROLLMENT_TYPE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    HAZARDOUS_WALKING_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PRV_WITHDRAWAL_CDE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CRNT_ENTER_CDE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    Z_349585 = table.Column<string>(type: "nvarchar(1)", maxLength: 1, nullable: true),
                    SR_USER_CODE_DD_23 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_CODE_DD_24 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_23 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_ENR_USER_DD_24 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    RECEIVER_DISTRICT = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    NO_SHOW_COMMENT = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NO_SHOW_RECEIVER_DISTRICT = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    NO_SHOW_RECEIVER_SCHOOL = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    INACTIVATE_COMMENT = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NO_SHOW_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SCHED_WEIGHT = table.Column<decimal>(type: "numeric(4,2)", nullable: true),
                    DISC_DET_HOURS = table.Column<decimal>(type: "numeric(6,2)", nullable: true),
                    DISC_DET_HOURS_SERVED = table.Column<decimal>(type: "numeric(6,2)", nullable: true),
                    SCHED_PATHWAY_HOUSE = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    SCHED_PATHWAY_TEAM = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    PRIOR_SCHOOL_DISTRICT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PRIOR_SCHOOL_STATE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PRIOR_SCHOOL_COUNTRY = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    STUDENT_OFFENDER_TRANSFER = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    EDUCATIONAL_CHOICE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DISASTER_AFFECTED_STUDENT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    PICK_UP_VEHICLE_CAT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    DROP_OFF_VEHICLE_CAT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    TRANSPORT_MEMBERSHIP_CAT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    INTNSV_SUPP_SVC_SEM1 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    INTNSV_SUPP_SVC_SEM2 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    INTNSV_SUPP_SVC_SUM = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    INTNSV_SUPP_SVC_BGN = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    NEXT_ATTEND_PERMIT_CODE = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    NEXT_ATTEND_PERMIT_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    NEXT_CONCURRENT_SCHOOL_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    SR_ENR_USER_CHECK_11 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_12 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_13 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_14 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    SR_ENR_USER_CHECK_15 = table.Column<string>(type: "char(1)", unicode: false, fixedLength: true, maxLength: 1, nullable: false),
                    EL_CASE_MGR_GU = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    EL_CASE_MGR_ASSN_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    SCHD_STATUS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    SR_USER_NUM_EXT_1 = table.Column<decimal>(type: "numeric(10,4)", nullable: true),
                    RESIDENT_STATUS = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CAREER_ACADEMY_1 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CAREER_ACADEMY_2 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    CAREER_ACADEMY_3 = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    GRD_PROMO_STAT_EXEMPT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    GRD_PROMO_STAT = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    TYPE_OF_INSTRUCTION = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    IN_PERSON_PERCENT_TIME = table.Column<decimal>(type: "numeric(8,3)", nullable: true),
                    REMOTE_PERCENT_TIME = table.Column<decimal>(type: "numeric(8,3)", nullable: true),
                    HYBRID_PATTERN = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: true),
                    RES_WAIVER_REASON = table.Column<string>(type: "nvarchar(5)", maxLength: 5, nullable: true),
                    RES_WAIVER_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true),
                    PICK_UP_GRID_CODE = table.Column<string>(type: "char(10)", unicode: false, fixedLength: true, maxLength: 10, nullable: true),
                    DROP_OFF_GRID_CODE = table.Column<string>(type: "char(10)", unicode: false, fixedLength: true, maxLength: 10, nullable: true),
                    LAST_COVID_CONTACT_DATE = table.Column<DateTime>(type: "smalldatetime", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("EPC_STU_SCH_YR_P", x => x.STUDENT_SCHOOL_YEAR_GU);
                    table.ForeignKey(
                        name: "EPC_STU_SCH_YR_F1",
                        column: x => x.STUDENT_GU,
                        principalSchema: "rev",
                        principalTable: "EPC_STU",
                        principalColumn: "STUDENT_GU");
                    table.ForeignKey(
                        name: "EPC_STU_SCH_YR_F4",
                        column: x => x.YEAR_GU,
                        principalSchema: "rev",
                        principalTable: "REV_YEAR",
                        principalColumn: "YEAR_GU");
                    table.ForeignKey(
                        name: "EPC_STU_SCH_YR_F5",
                        column: x => x.ORGANIZATION_YEAR_GU,
                        principalSchema: "rev",
                        principalTable: "REV_ORGANIZATION_YEAR",
                        principalColumn: "ORGANIZATION_YEAR_GU");
                });

            migrationBuilder.CreateIndex(
                name: "EPC_STU_C1",
                schema: "rev",
                table: "EPC_STU",
                column: "SIS_NUMBER",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "EPC_STU_I1",
                schema: "rev",
                table: "EPC_STU",
                column: "ENR_RESTRICT_ORGANIZATION_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_I2",
                schema: "rev",
                table: "EPC_STU",
                column: "GRAD_REQ_DEF_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_I3",
                schema: "rev",
                table: "EPC_STU",
                column: "PRIMARY_COMM_FAMILY_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_I4",
                schema: "rev",
                table: "EPC_STU",
                column: "ENROLL_RESIDENT_FAMILY_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_I5",
                schema: "rev",
                table: "EPC_STU",
                column: "CHILD_INITIAL_SCHOOL");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_a1",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                column: "GRADE");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_C1",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                columns: new[] { "STUDENT_GU", "ORGANIZATION_YEAR_GU" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_Cube",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                columns: new[] { "ORGANIZATION_YEAR_GU", "YEAR_GU" });

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_I1",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                columns: new[] { "ORGANIZATION_YEAR_GU", "STUDENT_GU" });

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_I2",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                columns: new[] { "ORGANIZATION_YEAR_GU", "OLD_SIS_STUDENT_NUM" });

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_I3",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                column: "COUNSELOR_SCHOOL_YEAR_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_I4",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                column: "YEAR_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_I5",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                column: "TRACK_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_I6",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                column: "PICK_UP_ADDRESS_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_I7",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                column: "DROP_OFF_ADDRESS_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_I8",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                column: "PICK_UP_SCHOOL_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_I9",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                column: "DROP_OFF_SCHOOL_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_IA",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                column: "LAST_HOMEROOM_SECTION_GU");

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_IB",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                columns: new[] { "ORGANIZATION_YEAR_GU", "LEAVE_DATE" });

            migrationBuilder.CreateIndex(
                name: "EPC_STU_SCH_YR_IC",
                schema: "rev",
                table: "EPC_STU_SCH_YR",
                columns: new[] { "STUDENT_GU", "ORGANIZATION_YEAR_GU", "LAST_HOMEROOM_SECTION_GU", "GRADE" });

            migrationBuilder.CreateIndex(
                name: "REV_ORGANIZATION_I1",
                schema: "rev",
                table: "REV_ORGANIZATION",
                column: "ADDRESS_GU");

            migrationBuilder.CreateIndex(
                name: "REV_ORGANIZATION_I2",
                schema: "rev",
                table: "REV_ORGANIZATION",
                column: "EDFI_KEY_GU");

            migrationBuilder.CreateIndex(
                name: "REV_ORGANIZATION_YEAR_C1",
                schema: "rev",
                table: "REV_ORGANIZATION_YEAR",
                columns: new[] { "ORGANIZATION_GU", "YEAR_GU" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "REV_ORGANIZATION_YEAR_I1",
                schema: "rev",
                table: "REV_ORGANIZATION_YEAR",
                column: "YEAR_GU");

            migrationBuilder.CreateIndex(
                name: "REV_PERSON_I1",
                schema: "rev",
                table: "REV_PERSON",
                columns: new[] { "LAST_NAME", "FIRST_NAME", "MIDDLE_NAME", "PERSON_GU" });

            migrationBuilder.CreateIndex(
                name: "REV_PERSON_I2",
                schema: "rev",
                table: "REV_PERSON",
                columns: new[] { "SCROLL_COMPOSITE_KEY", "PERSON_GU" });

            migrationBuilder.CreateIndex(
                name: "REV_PERSON_I3",
                schema: "rev",
                table: "REV_PERSON",
                column: "HOME_ADDRESS_GU");

            migrationBuilder.CreateIndex(
                name: "REV_PERSON_I4",
                schema: "rev",
                table: "REV_PERSON",
                column: "MAIL_ADDRESS_GU");

            migrationBuilder.CreateIndex(
                name: "REV_PERSON_I5",
                schema: "rev",
                table: "REV_PERSON",
                column: "WORK_ADDRESS_GU");

            migrationBuilder.CreateIndex(
                name: "REV_PERSON_I6",
                schema: "rev",
                table: "REV_PERSON",
                column: "EMAIL");

            migrationBuilder.CreateIndex(
                name: "REV_YEAR_C1",
                schema: "rev",
                table: "REV_YEAR",
                columns: new[] { "SCHOOL_YEAR", "EXTENSION" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EPC_STU_SCH_YR",
                schema: "rev");

            migrationBuilder.DropTable(
                name: "EPC_STU",
                schema: "rev");

            migrationBuilder.DropTable(
                name: "REV_PERSON",
                schema: "rev");

            migrationBuilder.DropTable(
                name: "REV_ORGANIZATION_YEAR",
                schema: "rev");

            migrationBuilder.DropTable(
                name: "REV_ORGANIZATION",
                schema: "rev");

            migrationBuilder.DropTable(
                name: "REV_YEAR",
                schema: "rev");
        }
    }
}
